[wokwi]
version = 1
elf = src/urbansense_cp2.ino
firmware = src/urbansense_cp2.ino

[[library]]
name = "DHT sensor library"
version = "1.4.4"

[[library]]
name = "Adafruit Unified Sensor"
version = "1.1.14"

[[library]]
name = "LiquidCrystal I2C"
version = "1.1.2"

[[library]]
name = "PubSubClient"
version = "2.8"

[[library]]
name = "ArduinoJson"
version = "6.21.3"
